# Generated by Django 2.2.7 on 2020-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default='39949', max_length=200)),
                ('image_title_kz', models.CharField(max_length=300)),
                ('image_title_eng', models.CharField(max_length=300)),
                ('image_title_ru', models.CharField(max_length=300)),
                ('text_kz', models.TextField(verbose_name='Text in kazakh')),
                ('text_eng', models.TextField(verbose_name='Text in eng')),
                ('text_ru', models.TextField(verbose_name='Text in russian')),
                ('gallery_image', models.FileField(null=True, upload_to='media/', verbose_name='Gallery photo')),
                ('audio_kz', models.FileField(null=True, upload_to='files/', verbose_name='Audio in kazakh')),
                ('audio_eng', models.FileField(null=True, upload_to='files/', verbose_name='Audio in english')),
                ('audio_ru', models.FileField(null=True, upload_to='files/', verbose_name='Audio in russian')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='InfoGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_title', models.CharField(max_length=200)),
                ('kz', models.TextField(verbose_name='Information in kazakh')),
                ('eng', models.TextField(verbose_name='Information in eng')),
                ('ru', models.TextField(verbose_name='Information in russian')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
            },
        ),
    ]
